name: Pre-generate preview link

permissions:
    pull-requests: write

on:
    pull_request:
        types: [opened, synchronize]

concurrency:
    group: cloudflare-pages-verify-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    verify_pull_request:
        runs-on: Ubuntu-latest
        steps:
            - name: Post preview link
              run: |
                  branchName=$(echo ${{ github.head_ref }} | sed 's/[\/_]/-/g')
                  echo "✨ Preview link: https://$branchName.deriv-com-preview-links.pages.dev"
