name: Pre-generate preview link

permissions:
    pull-requests: write

on:
    pull_request:
        types: [opened, synchronize]

concurrency:
    group: cloudflare-pages-verify-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    verify_pull_request:
        runs-on: Ubuntu-latest
        steps:
            - name: Post preview link
              run: |
                  branchName=$(echo ${{ github.head_ref }} | sed 's/[\/_]/-/g')
                  curl -L \
                      -X POST \
                      -H "Accept: application/vnd.github+json" \
                      -H "Authorization: Bearer ${{ github.token }}" \
                      -H "X-GitHub-Api-Version: 2022-11-28" \
                      "https://api.github.com/repos/binary-com/deriv-com/issues/${{github.event.pull_request.number}}/comments" \
                      -d "{\"body\": \"https://$branchName.deriv-com-test-links.pages.dev\" }"
